### ISSUE TITLE
V6

### ISSUE THREAD

**Issue by i-like-robots** [i-like-robots/react-tags#106]
This is a catch-all issue tracking V6 changes and bug fixes.

- [x] >= React 16 (#113)
- [x] Remove `autofocus` option for a11y reasons
- [x] Merge `delimiters` and `delimiterChars` options using `KeyboardEvent.key`
- [x] event callbacks should be re-named from `handleX` to `onX` (#91)
- [x] `handleInputChange` should be re-named `onInput`
- [x] Make `listBoxId` configurable
- [x] Support ES6 modules, `pkg.module` (#112)
- [x] Refactor option filtering into top-level component (#115)
- [x] Allow all text to be configurable (CC #154)
- [x] Custom suggestion component (CC #117)
- [x] Refactor class names out of state to avoid creating new objects on each prop change (#147)
- [x] Remove `clearInputOnDelete` option and don't clear the input when deleting a tag (#155)

**Comment by mklopets** [comment]
Is there a plan to release this?

**Comment by drichar** [comment]
Would love to utilize the custom suggestion component! Will 6.0 be released?

**Comment by i-like-robots** [comment]
I've published `react-tag-autocomplete@6.0.0-beta.0` to npm, please give it a try and let me know if there are any issues!

**Comment by theJian** [comment]
@i-like-robots Any plan to refactor using Hooks? Maybe starting with examples?

**Comment by i-like-robots** [comment]
@theJian No not yet. Starting with the examples sounds like a fine idea though.

**Comment by filippofilip95** [comment]
Any update on this ? :)

**Comment by filippofilip95** [comment]
When do you plan to merge this? :)

**Comment by i-like-robots** [comment]
Unfortunately I've not received any feedback on the beta release so I have been reluctant to release it. If you would like to try it then there are instructions in the readme 😄 :

https://github.com/i-like-robots/react-tags/tree/6.0#installation

**Comment by filippofilip95** [comment]
Thanks for the quick reply :) I've tested it now and it works like charm :)  Just followed your migration instructions :) 

Our implementation is minimal. But I can confirm that this works :)

<img width="343" alt="Screen Shot 2019-08-23 at 1 23 08 PM" src="https://user-images.githubusercontent.com/10739349/63589357-315f8800-c5a9-11e9-992f-53a4b789b481.png">

**Comment by coxom** [comment]
When using an async search to fetch the suggestions the component won't work correctly and will get out of sync with the suggestions provided via props.
From the code seems like it's not looking into changes from suggestions to update its internal state.

PS: Seems like the beta version is now the default version installed when you do "npm i react-tag-autocomplete". Took me a while to understand why handleInputChange was not working.

**Comment by i-like-robots** [comment]
Thanks for the heads up about incorrect npm distribution tags @coxom, this has been corrected [here](https://www.npmjs.com/package/react-tag-autocomplete?activeTab=versions).

**Comment by insekticid** [comment]
@coxom I solved onInput async fetch with  <ReactTags ref={this.tagsRef} 
@i-like-robots is this bug?

```
onInput = (query) => {
            return fetch(`/search/?q=${query}`).then(result => result.json()).then((suggestions) => {
                        this.tagsRef.current.setState({ query, options: suggestions, suggestions });
```
